Attribute VB_Name = "Module1"
Option Explicit

Private Const VERSION_RANGE_NAME As String = "InterfaceVersion"
Private Const OUTPUT_PATH_RANGE_NAME As String = "OutputPath"
Private Const DEFAULT_OUTPUT_FILE As String = "IrrigationHeader.h"

Sub GenerateCHeader()

    Dim ws As Worksheet
    Dim outputFile As String
    Dim outputPathInput As String
    Dim outputFolder As String
    Dim interfaceVersion As String
    Dim i As Long, J As Long, startRow As Long
    Dim fileContent As String
    Dim blockName As String
    Dim blockNamePrefix As String
    Dim blockNameLen As String
    Dim structName As String
    
    Set ws = ThisWorkbook.ActiveSheet
    interfaceVersion = GetNamedRangeText(VERSION_RANGE_NAME)
    If Not IsValidVersion(interfaceVersion) Then
        MsgBox "Version in named range '" & VERSION_RANGE_NAME & "' must be in format X.Y.Z (example: 1.0.0).", vbExclamation
        Exit Sub
    End If

    outputPathInput = GetNamedRangeText(OUTPUT_PATH_RANGE_NAME)
    If outputPathInput = "" Then
        outputPathInput = ThisWorkbook.Path
    End If

    outputFile = ResolveOutputFile(outputPathInput)
    outputFolder = Left$(outputFile, InStrRev(outputFile, "\") - 1)
    If Dir(outputFolder, vbDirectory) = "" Then
        MsgBox "Output folder does not exist: " & outputFolder, vbExclamation
        Exit Sub
    End If
    
     i = 1 ' Initialize row pointer
    fileContent = "" ' Initialize the file content

    fileContent = fileContent & "// AUTO-GENERATED by GenerateCHeader" & vbCrLf
    fileContent = fileContent & "// Interface Version: " & interfaceVersion & vbCrLf
    fileContent = fileContent & "// Generated: " & Format(Now, "yyyy-mm-dd hh:nn:ss") & vbCrLf
    fileContent = fileContent & "#define INTERFACE_VERSION """ & interfaceVersion & """" & vbCrLf & vbCrLf
    
    Do While Not IsEmpty(ws.Cells(i, 1))
    
    
            ' Extract block name and format it
            blockName = Replace(ws.Cells(i + 1, 2).Value, " ", "") & ""
            blockNamePrefix = Replace(ws.Cells(i + 1, 2).Value, " ", "_") & "_"
            blockNameLen = Replace(ws.Cells(i + 8, 2).Value, " ", "_") & "_"
            structName = Replace(ws.Cells(i + 3, 2).Value, "", "")
            ' Header content
            fileContent = fileContent & "/*" & vbCr
            startRow = i
            For J = startRow To startRow + 8 ' Loop till 9 to avoid adding an extra line break for the 10th line
                fileContent = fileContent & "* " & ws.Cells(J, 1).Value & ": " & ws.Cells(J, 2).Value & vbCr
            Next J
            i = J
            
            ' Table content for the block
            Do While ws.Cells(i, 1).Value <> "" ' Check for blank cell in column 1 to determine the end of data
                fileContent = fileContent & "*  " & ws.Cells(i, 1).Value & "        " & ws.Cells(i, 2).Value & "            " & ws.Cells(i, 3).Value & "        " & ws.Cells(i, 4).Value & "        " & ws.Cells(i, 5).Value & "        " & ws.Cells(i, 6).Value & "        " & ws.Cells(i, 7).Value & "        " & ws.Cells(i, 8).Value & vbCr
                i = i + 1
            Loop
            fileContent = fileContent & "*/" & vbCrLf
        
             ' Definitions for the block
            fileContent = fileContent & "const char " & UCase(blockNamePrefix) & "CLIENTID[] =    """ & ws.Cells(startRow + 6, 2).Value & """ " & ";" & vbCr
            
            ' Check if the cell for the block name is not empty
            If Trim(ws.Cells(startRow + 7, 2).Value) <> "" Then
                ' If not empty, prepend "mwp/" to the value from the cell
                fileContent = fileContent & "const char " & UCase(blockNamePrefix) & "TOPICID[] =  ""mwp/" & ws.Cells(startRow + 7, 2).Value & """" & ";" & vbCr
                fileContent = fileContent & "const char " & UCase(blockNamePrefix) & "JSONID[] =  """ & BuildJsonIdForBlock("mwp/json/" & ws.Cells(startRow + 7, 2).Value, blockNamePrefix, interfaceVersion) & """" & ";" & vbCr
            Else
                ' If the cell is empty, build the topic ID using a different method
                fileContent = fileContent & "const char " & UCase(blockNamePrefix) & "TOPICID[] =  ""mwp/" & ws.Cells(startRow + 5, 2).Value & "/" & ws.Cells(startRow + 4, 2).Value & "/" & ws.Cells(startRow + 3, 2).Value & "/" & ws.Cells(startRow, 2).Value & """" & ";" & vbCr
                fileContent = fileContent & "const char " & UCase(blockNamePrefix) & "JSONID[] =  """ & BuildJsonIdForBlock("mwp/json/" & ws.Cells(startRow + 5, 2).Value & "/" & ws.Cells(startRow + 4, 2).Value & "/" & ws.Cells(startRow + 3, 2).Value & "/" & ws.Cells(startRow, 2).Value, blockNamePrefix, interfaceVersion) & """" & ";" & vbCr
            End If

            fileContent = fileContent & "#define " & UCase(blockNamePrefix) & "LEN " & ws.Cells(startRow + 8, 2).Value & vbCrLf
            fileContent = fileContent & "union   " & UCase(blockNamePrefix) & "  {" & vbCr
            fileContent = fileContent & "   " & ws.Cells(startRow + 10, 2).Value & "     data_payload[" & UCase(blockNamePrefix) & "LEN] ;" & vbCrLf
        
        ' Struct definitions for the block
        fileContent = fileContent & "   struct  {" & vbCr
        J = startRow + 10
        While ws.Cells(J, 3).Value <> "" And Not IsEmpty(ws.Cells(J, 3))
            fileContent = fileContent & "      " & ws.Cells(J, 2).Value & "   " & ws.Cells(J, 3).Value & vbTab & ";" & vbTab & vbTab & "//   " & ws.Cells(J, 9).Value & vbCr
            J = J + 1
        Wend
        fileContent = fileContent & "   }  " & LCase(structName) & "  ;" & vbCr
        fileContent = fileContent & "}  ;" & vbCr
        fileContent = fileContent & "union  " & UCase(blockNamePrefix) & "  " & blockName & "_  ;" & vbCrLf

        ' Variable names array for the block
        fileContent = fileContent & "char* " & LCase(blockNamePrefix) & "ClientData_var_name [] = { " & vbCr
        J = startRow + 10
        While ws.Cells(J, 3).Value <> "" And Not IsEmpty(ws.Cells(J, 3))
            If ws.Cells(startRow, 2).Value <> "" Then
                fileContent = fileContent & "    """ & ws.Cells(startRow, 2) & ":" & ws.Cells(J, 3).Value & """," & vbCr
            Else
                fileContent = fileContent & "    """ & ws.Cells(J, 3).Value & """," & vbCr
            End If
            J = J + 1
        Wend
        fileContent = fileContent & "}  ;" & vbCrLf

        ' Move pointer to next block or end
        i = J + 1

    Loop
    
    ' Write to file
    Dim fileNum As Integer
    fileNum = FreeFile
    Open outputFile For Output As fileNum
    Print #fileNum, fileContent
    Close fileNum

    MsgBox "Header file generated successfully!" & vbCrLf & _
           "Version: " & interfaceVersion & vbCrLf & _
           "Output: " & outputFile, vbInformation

End Sub

Private Function GetNamedRangeText(ByVal rangeName As String) As String
    On Error GoTo MissingRange
    GetNamedRangeText = Trim$(CStr(ThisWorkbook.Names(rangeName).RefersToRange.Value))
    Exit Function

MissingRange:
    GetNamedRangeText = ""
End Function

Private Function ResolveOutputFile(ByVal outputPathInput As String) As String
    Dim p As String

    p = Trim$(outputPathInput)
    If LCase$(Right$(p, 2)) = ".h" Then
        ResolveOutputFile = p
    Else
        If Right$(p, 1) <> "\" Then
            p = p & "\"
        End If
        ResolveOutputFile = p & DEFAULT_OUTPUT_FILE
    End If
End Function

Private Function IsValidVersion(ByVal versionText As String) As Boolean
    Dim parts() As String
    Dim k As Long

    parts = Split(versionText, ".")
    If UBound(parts) <> 2 Then
        IsValidVersion = False
        Exit Function
    End If

    For k = LBound(parts) To UBound(parts)
        If parts(k) = "" Or Not IsNumeric(parts(k)) Then
            IsValidVersion = False
            Exit Function
        End If
    Next k

    IsValidVersion = True
End Function

Private Function BuildJsonIdForBlock(ByVal baseJsonId As String, ByVal blockNamePrefix As String, ByVal interfaceVersion As String) As String
    Dim versionSuffix As String

    BuildJsonIdForBlock = baseJsonId

    ' Only version the monitor JSON topic.
    If LCase$(Trim$(blockNamePrefix)) <> "monitor_" Then
        Exit Function
    End If

    versionSuffix = "_v" & Replace(interfaceVersion, ".", "_")

    If Right$(baseJsonId, 1) = "/" Then
        BuildJsonIdForBlock = Left$(baseJsonId, Len(baseJsonId) - 1) & versionSuffix & "/"
    Else
        BuildJsonIdForBlock = baseJsonId & versionSuffix
    End If
End Function


