// alarm_config.h - AUTO-GENERATED by generate_alarms.py. DO NOT EDIT.

#ifndef ALARM_CONFIG_H
#define ALARM_CONFIG_H

#include <stdbool.h>

#define ALARM_COUNT 21

typedef enum {
    ALARM_TYPE_INFO,
    ALARM_TYPE_WARN,
    ALARM_TYPE_CRITICAL
} AlarmType;

typedef struct {
    const int id;
    const AlarmType type;
    const char* label;
    const char* eventMessage;
    const int trigger_delay_seconds;
} AlarmInfo;

extern const AlarmInfo alarmInfo[ALARM_COUNT];

#endif // ALARM_CONFIG_H